name: 🐛 Bug Report
description: File a bug report to help us improve EternalCombat
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please ensure that you have searched the existing issues to see if this bug has already been reported.

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
      placeholder: I was doing X and Y happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Please provide a step-by-step guide to reproduce the issue.
      placeholder: |
        1. Launch the server
        2. Tag yourself using the '/combat tag' command
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Video
      description: If applicable, add screenshots or a video to help explain your problem.

  - type: dropdown
    id: server-software
    attributes:
      label: Server Software
      description: What server software are you using?
      options:
        - Paper
        - Purpur
        - Spigot
        - Folia
        - Other (please specify in logs)
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running? (e.g. 1.21.11)
      placeholder: 1.21.11
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of EternalCombat are you running? (Check with /eternalcombat version)
      placeholder: v2.4.1
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack Trace
      description: Please paste any relevant logs or stack traces here. Use a pastebin service if the log is too long.
      render: shell
